import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            <button className={styles.button}>Test 1</button>
            <button className={styles.button}>Test 2</button>
            <button className={styles.button}>Test 3</button>
            <button className={styles.button}>Test 4</button>
            <button className={styles.button}>Test 5</button>
          </div>
        </div>
      </main>
    </>
  )
}
